export enum TYPE {
  OPEN_MODAL_CONFIRM = 'OPEN_MODAL_CONFIRM',
  CLOSE_MODAL_CONFIRM = 'CLOSE_MODAL_CONFIRM',
  OPEN_MODAL_FORM = 'OPEN_MODAL_FORM',
  CLOSE_MODAL_FORM = 'CLOSE_MODAL_FORM',
}

interface OPEN_MODAL_CONFIRM {
  type: TYPE.OPEN_MODAL_CONFIRM
}

interface CLOSE_MODAL_CONFIRM {
  type: TYPE.CLOSE_MODAL_CONFIRM
}

interface OPEN_MODAL_FORM {
  type: TYPE.OPEN_MODAL_FORM
}

interface CLOSE_MODAL_FORM {
  type: TYPE.CLOSE_MODAL_FORM
}

export type Action = OPEN_MODAL_CONFIRM | CLOSE_MODAL_CONFIRM | OPEN_MODAL_FORM | CLOSE_MODAL_FORM
